package model;
// Generated 18 dic 2023 18:29:18 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Generated;

/**
 * Clientes generated by hbm2java
 */


@Table(name = "Clientes")
public class Clientes implements java.io.Serializable {
        @Id
        @Column(name = "idCliente")
	private Integer idCliente;
	private Usuarios usuarios;
        @Column(name = "nombreCliente")
	private String nombreCliente;
        private int id_usuario;
	private Set ventases = new HashSet(0);

	public Clientes() {
	}

        public Clientes(Usuarios usuarios, String nombreCliente) {
		this.usuarios = usuarios;
		this.nombreCliente = nombreCliente;
		this.ventases = ventases;
	}
        
	public Clientes(Usuarios usuarios, String nombreCliente, int id_usuario, Set ventases) {
		this.usuarios = usuarios;
		this.nombreCliente = nombreCliente;
                this.id_usuario = id_usuario;
		this.ventases = ventases;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

        public int getId_usuario() {
            return id_usuario;
        }

        public void setId_usuario(int id_usuario) {
            this.id_usuario = id_usuario;
        }

        
        
	public Set getVentases() {
		return this.ventases;
	}

	public void setVentases(Set ventases) {
		this.ventases = ventases;
	}

}
