package model;
// Generated 18 dic 2023 18:29:18 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Juegos generated by hbm2java
 */
public class Juegos implements java.io.Serializable {

	private Integer idJuego;
	private Usuarios usuarios;
	private String nombreJuego;
	private String plataforma;
	private double precio;
        private int id_usuario;
	private Set ventases = new HashSet(0);

	public Juegos() {
	}
        
        public Juegos(Usuarios usuarios, String nombreJuego, String plataforma, double precio) {
            this.usuarios = usuarios;
            this.nombreJuego = nombreJuego;
            this.plataforma = plataforma;
            this.precio = precio;
            
	}

	public Juegos(Usuarios usuarios, String nombreJuego, String plataforma, double precio, int id_usuario, Set ventases) {
		this.usuarios = usuarios;
		this.nombreJuego = nombreJuego;
		this.plataforma = plataforma;
		this.precio = precio;
                this.id_usuario = id_usuario;
		this.ventases = ventases;
	}

	public Integer getIdJuego() {
		return this.idJuego;
	}

	public void setIdJuego(Integer idJuego) {
		this.idJuego = idJuego;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getNombreJuego() {
		return this.nombreJuego;
	}

	public void setNombreJuego(String nombreJuego) {
		this.nombreJuego = nombreJuego;
	}

	public String getPlataforma() {
		return this.plataforma;
	}

	public void setPlataforma(String plataforma) {
		this.plataforma = plataforma;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

        public int getId_usuario() {
            return id_usuario;
        }

        public void setId_usuario(int id_usuario) {
            this.id_usuario = id_usuario;
        }
        
        

	public Set getVentases() {
		return this.ventases;
	}

	public void setVentases(Set ventases) {
		this.ventases = ventases;
	}

}
