package model;
// Generated 18 dic 2023 18:29:18 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * VentasId generated by hbm2java
 */
@Embeddable
public class VentasId implements java.io.Serializable {
        
        private int idVenta;
	private Date fechaVenta;
	private int idCliente;
	private int idJuego;
	private double precioVenta;
        
	public VentasId() {
	}

	public VentasId(int idVenta, Date fechaVenta, int idCliente, int idJuego, double precioVenta) {
		this.idVenta = idVenta;
                this.fechaVenta = fechaVenta;
		this.idCliente = idCliente;
		this.idJuego = idJuego;
		this.precioVenta = precioVenta;
	}

        public int getIdVenta() {
            return idVenta;
        }

        public void setIdVenta(int idVenta) {
            this.idVenta = idVenta;
        }

	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public int getIdJuego() {
		return this.idJuego;
	}

	public void setIdJuego(int idJuego) {
		this.idJuego = idJuego;
	}

	public double getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(double precioVenta) {
		this.precioVenta = precioVenta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VentasId))
			return false;
		VentasId castOther = (VentasId) other;

		return ((this.getIdCliente() == castOther.getIdCliente()) && (this.getFechaVenta() == castOther.getFechaVenta()) || (this.getFechaVenta() != null
				&& castOther.getFechaVenta() != null && this.getFechaVenta().equals(castOther.getFechaVenta())))
				&& (this.getIdCliente() == castOther.getIdCliente()) && (this.getIdJuego() == castOther.getIdJuego())
				&& (this.getPrecioVenta() == castOther.getPrecioVenta());
	}

	public int hashCode() {
		int result = 17;
                result = 37 * result + this.getIdVenta();
		result = 37 * result + (getFechaVenta() == null ? 0 : this.getFechaVenta().hashCode());
		result = 37 * result + this.getIdCliente();
		result = 37 * result + this.getIdJuego();
		result = 37 * result + (int) this.getPrecioVenta();
		return result;
	}

}
