package model;
// Generated 18 dic 2023 18:29:18 by Hibernate Tools 6.3.1.Final


import javax.persistence.EmbeddedId;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Entity;


/**
 * Ventas generated by hbm2java
 */

@Entity
public class Ventas implements java.io.Serializable {
       
	private VentasId id;
        @ManyToOne
        @JoinColumn(name = "id_juego")
	private Juegos juegos;
        @ManyToOne
        @JoinColumn(name = "id_cliente")
	private Clientes clientes;

	public Ventas() {
	}
        
       

	public Ventas(VentasId id, Juegos juegos, Clientes clientes) {
		this.id = id;
		this.juegos = juegos;
		this.clientes = clientes;
	}

	public VentasId getId() {
		return this.id;
	}

	public void setId(VentasId id) {
		this.id = id;
	}

	public Juegos getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Juegos juegos) {
		this.juegos = juegos;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

}
