package model;
// Generated 18 dic 2023 18:29:18 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer idCliente;
	private Usuarios usuarios;
	private String nombreCliente;
	private Set ventases = new HashSet(0);

	public Clientes() {
	}

	public Clientes(Usuarios usuarios, String nombreCliente, Set ventases) {
		this.usuarios = usuarios;
		this.nombreCliente = nombreCliente;
		this.ventases = ventases;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	public Set getVentases() {
		return this.ventases;
	}

	public void setVentases(Set ventases) {
		this.ventases = ventases;
	}

}
